/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KatalogIndexRouteImport } from './routes/katalog/index'
import { Route as KatalogIdRouteImport } from './routes/katalog/$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminAuthenticatedDashboardRouteImport } from './routes/admin._authenticated.dashboard'
import { Route as AdminAuthenticatedCarsRouteImport } from './routes/admin._authenticated.cars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogIndexRoute = KatalogIndexRouteImport.update({
  id: '/katalog/',
  path: '/katalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogIdRoute = KatalogIdRouteImport.update({
  id: '/katalog/$id',
  path: '/katalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedDashboardRoute =
  AdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCarsRoute = AdminAuthenticatedCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/katalog/$id': typeof KatalogIdRoute
  '/katalog/': typeof KatalogIndexRoute
  '/admin/cars': typeof AdminAuthenticatedCarsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/katalog/$id': typeof KatalogIdRoute
  '/katalog': typeof KatalogIndexRoute
  '/admin/cars': typeof AdminAuthenticatedCarsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/katalog/$id': typeof KatalogIdRoute
  '/katalog/': typeof KatalogIndexRoute
  '/admin/_authenticated/cars': typeof AdminAuthenticatedCarsRoute
  '/admin/_authenticated/dashboard': typeof AdminAuthenticatedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/katalog/$id'
    | '/katalog/'
    | '/admin/cars'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/katalog/$id'
    | '/katalog'
    | '/admin/cars'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/katalog/$id'
    | '/katalog/'
    | '/admin/_authenticated/cars'
    | '/admin/_authenticated/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  KatalogIdRoute: typeof KatalogIdRoute
  KatalogIndexRoute: typeof KatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/': {
      id: '/katalog/'
      path: '/katalog'
      fullPath: '/katalog/'
      preLoaderRoute: typeof KatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/$id': {
      id: '/katalog/$id'
      path: '/katalog/$id'
      fullPath: '/katalog/$id'
      preLoaderRoute: typeof KatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/dashboard': {
      id: '/admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/cars': {
      id: '/admin/_authenticated/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminAuthenticatedCarsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedCarsRoute: typeof AdminAuthenticatedCarsRoute
  AdminAuthenticatedDashboardRoute: typeof AdminAuthenticatedDashboardRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedCarsRoute: AdminAuthenticatedCarsRoute,
  AdminAuthenticatedDashboardRoute: AdminAuthenticatedDashboardRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  KatalogIdRoute: KatalogIdRoute,
  KatalogIndexRoute: KatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
